name: Build Native Image

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the project
        run: |
          mvn package -Pnative

      - name: Find JAR file
        id: jarfile
        run: |
          echo "JAR_PATH=$(ls target/java-hdfs-fuse*.jar | head -n 1)" >> $GITHUB_ENV
          echo Found JAR file $JAR_PATH

      - name: Create native image
        run: |
          native-image --no-fallback -jar ${{ env.JAR_PATH }} hdfs-mount

      - name: Archive native image
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: hdfs-mount
          path: hdfs-mount

  release:
    runs-on: ubuntu-latest
    needs: build-native
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download native image
        uses: actions/download-artifact@v3
        with:
          name: native-image

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release for tag ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hdfs-mount
          asset_name: hdfs-mount
          asset_content_type: application/octet-stream